### ISSUE TITLE
download.py issue

### ISSUE THREAD

**Issue by yrvelez** [nsarrazin/serge#102] opened 2023-03-28 22:58 UTC
### Bug description

Hello,

I have launched the container successfully, but I'm facing an issue when trying to execute the download.py script with the following command:

docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B

I'm receiving the following error message:
python3: can't open file '/usr/src/app/api/utils/download.py': [Errno 2] No such file or directory

I have tried to locate the download.py file using bash, but it doesn't seem to be present. I would appreciate any help in resolving this issue.

Thank you.

### Steps to reproduce

git clone https://github.com/nsarrazin/serge.git
cd serge

docker compose up --build -d
docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B

root@localhost:/home/serge# docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B
python3: can't open file '/usr/src/app/api/utils/download.py': [Errno 2] No such file or directory

### Environment Information

Docker version 23.0.1, build a5ee5b1
OS: Debian 11

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment] 2023-03-28 23:07
@nsarrazin This was caused by https://github.com/nsarrazin/serge/commit/b5c423fe590d10bd4cfa0ce7a07933ac4bd2b788

**Comment by IngwiePhoenix** [comment] 2023-03-28 23:59
When you open http://localhost:8008 you will see a Model Download button now. Use this.

Ran into this too. :)

**Comment by gerroon** [comment] 2023-03-29 00:08
@IngwiePhoenix  I used that to downoad the models but when I run a query it says it says "No such file or directory" I assume it downloaded them but it cant find the models. I am using the docker compose

**Comment by gerroon** [comment] 2023-03-29 01:44
I am getting this in the log, not sure if it is directly related to the error I gave about the missing downloads


```
serge-serge-1  | INFO:     PC:64351 - "GET /model/all HTTP/1.1" 200 OK                                                                                                                                                                                                                                                                                [9/1931]
serge-serge-1  | INFO:     PC:64350 - "GET /chat/0a63a51b-e439-43a9-87fb-62ca26ab01cc HTTP/1.1" 500 Internal Server Error                                                
serge-serge-1  | ERROR:    Exception in ASGI application                                                                                                                             
serge-serge-1  | Traceback (most recent call last):                                                                                                                                  
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi                                                                                                                                                                                                                                         
serge-serge-1  |     result = await app(  # type: ignore[func-returns-value]                                                                                                         
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__                                                          
serge-serge-1  |     return await self.app(scope, receive, send)                                                                                                                     
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__                                                                                                                                                                                                                                                          
serge-serge-1  |     await super().__call__(scope, receive, send)                                                                                                                    
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__                                                                   
serge-serge-1  |     await self.middleware_stack(scope, receive, send)                    
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__                                                              
serge-serge-1  |     raise exc                                                            
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__                                                              
serge-serge-1  |     await self.app(scope, receive, _send)                                
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__                                                                 
serge-serge-1  |     await self.app(scope, receive, send)                                 
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 109, in __call__                                                                
serge-serge-1  |     await response(scope, receive, send)                                 
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 270, in __call__                                                                      
serge-serge-1  |     async with anyio.create_task_group() as task_group:                                                                                                             
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__                                                                
serge-serge-1  |     raise exceptions[0]                                                  
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 273, in wrap                                                                          
serge-serge-1  |     await func()                                                         
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 134, in stream_response                                                         
serge-serge-1  |     return await super().stream_response(send)                           
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 262, in stream_response                                                               
serge-serge-1  |     async for chunk in self.body_iterator:                               
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 98, in body_stream                                                              
serge-serge-1  |     raise app_exc                                                        
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 70, in coro                                                                     
serge-serge-1  |     await self.app(scope, receive_or_disconnect, send_no_error)                                                                                                     
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__                                                           
serge-serge-1  |     raise exc                                                            
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__                                                           
serge-serge-1  |     await self.app(scope, receive, sender)                               
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__                                                         
serge-serge-1  |     raise e                                                              
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__                                                         
serge-serge-1  |     await self.app(scope, receive, send)                                 
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__                                                                        
serge-serge-1  |     await route.handle(scope, receive, send)                             
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 443, in handle                                                                          
serge-serge-1  |     await self.app(scope, receive, send)                                 
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__                                                                     
serge-serge-1  |     await super().__call__(scope, receive, send)                         
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__                                                                   
serge-serge-1  |     await self.middleware_stack(scope, receive, send)                    
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__                                                              
serge-serge-1  |     raise exc                                                            
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__                                                              
serge-serge-1  |     await self.app(scope, receive, _send)                                
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__                                                           
serge-serge-1  |     raise exc                                                            
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__                                                           
serge-serge-1  |     await self.app(scope, receive, sender)                               
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__                                                         
serge-serge-1  |     raise e                                                              
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__                                                         
serge-serge-1  |     await self.app(scope, receive, send)                                 
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__                                                                        
serge-serge-1  |     await route.handle(scope, receive, send)                             
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle                                                                          
serge-serge-1  |     await self.app(scope, receive, send)                                 
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app                                                                              
serge-serge-1  |     response = await func(request)                                       
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app                                                                               
serge-serge-1  |     raw_response = await run_endpoint_function(                          
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function                                                             
serge-serge-1  |     return await dependant.call(**values)                                
serge-serge-1  |   File "/usr/local/lib/python3.10/dist-packages/serge/routers/chat.py", line 93, in get_specific_chat                                                               
serge-serge-1  |     await chat.fetch_all_links()                                         
serge-serge-1  | AttributeError: 'NoneType' object has no attribute 'fetch_all_links'                                                                                                
serge-serge-1  | INFO:     PC:64351 - "GET /chat/ HTTP/1.1" 200 OK                                                                                                       
serge-serge-1  | INFO:     PC:64351 - "GET /chat/ HTTP/1.1" 200 OK                                                                                                       
serge-serge-1  | INFO:     PC:64351 - "GET /_app/version.json HTTP/1.1" 200 OK                                                                                           
serge-serge-1  | INFO:     PC:64351 - "GET /chat/7d7f6151-da7d-4cd5-849f-5c726dcd1051 HTTP/1.1" 200 OK                                                                   
serge-serge-1  | INFO:     PC:64351 - "DELETE /chat/7d7f6151-da7d-4cd5-849f-5c726dcd1051 HTTP/1.1" 200 OK                                                                
serge-serge-1  | INFO:     PC:64351 - "GET /model/all HTTP/1.1" 200 OK                                                                                                   
serge-serge-1  | INFO:     PC:64351 - "GET /chat/ HTTP/1.1" 200 OK                                                                                                       
serge-serge-1  | INFO:     PC:64347 - "GET /_app/immutable/entry/models-page.svelte.415c778a.js HTTP/1.1" 200 OK                                                         
serge-serge-1  | INFO:     PC:64372 - "GET /_app/immutable/chunks/_page.7421b4ba.js HTTP/1.1" 200 OK                                                                     
serge-serge-1  | INFO:     PC:64351 - "GET /_app/immutable/chunks/4.eff395e3.js HTTP/1.1" 200 OK                                                   

```

**Comment by IngwiePhoenix** [comment] 2023-03-29 07:26
> @IngwiePhoenix I used that to downoad the models but when I run a query it says it says "No such file or directory" I assume it downloaded them but it cant find the models. I am using the docker compose.

Shut down the container (`docker compose down`), pull the newest code (`git pull`) and restart **and** recreate (`docker compose up --build --force-recreate`). This will delete your prior model downloads but is basically a fresh start. Should reset your state to something that works! :)

**Comment by gaby** [comment] 2023-04-02 16:38
@yrvelez Can you close this since its fixed. Thanks

**Closed** 2023-04-03 23:12 UTC
Labels: bug
